// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sdbm_hash
std::vector < unsigned int > sdbm_hash(std::vector < std::string> x);
RcppExport SEXP hrbrmiscpp_sdbm_hash(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector < std::string> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sdbm_hash(x));
    return rcpp_result_gen;
END_RCPP
}
// djb2_hash
std::vector < unsigned int > djb2_hash(std::vector < std::string> x);
RcppExport SEXP hrbrmiscpp_djb2_hash(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector < std::string> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(djb2_hash(x));
    return rcpp_result_gen;
END_RCPP
}
// line_count
SEXP line_count(SEXP f);
RcppExport SEXP hrbrmiscpp_line_count(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(line_count(f));
    return rcpp_result_gen;
END_RCPP
}
