# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' SDBM Hash Function
#'
#' @param x character vector of strings to hash
#' @return numeric vector of the hashes of \code{x}
#' @export
#' @examples
#' setdiff(sdbm_hash(state.name), sdbm_hash(state.name))
#' ## numeric(0)
sdbm_hash <- function(x) {
    .Call('hrbrmiscpp_sdbm_hash', PACKAGE = 'hrbrmiscpp', x)
}

#' DJB2 Hash Function
#'
#' @param x character vector of strings to hash
#' @return numeric vector of the hashes of \code{x}
#' @export
#' @examples
#' setdiff(djb2_hash(state.name), djb2_hash(state.name))
#' ## numeric(0)
djb2_hash <- function(x) {
    .Call('hrbrmiscpp_djb2_hash', PACKAGE = 'hrbrmiscpp', x)
}

#' Count lines (fast, like "wc")
#'
#' @param f full path to file
#' @export
#' @examples
#' line_count(system.file("extdata", "lines.csv", package = "hrbrmiscpp"))
line_count <- function(f) {
    .Call('hrbrmiscpp_line_count', PACKAGE = 'hrbrmiscpp', f)
}

