# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Personal hash function
#'
#' @param x character vector of strings to hash
#' @return numeric vector of the hashes of \code{x}
#' @export
#' @examples
#' setdiff(sdbm_hash(state.name), sdbm_hash(state.name))
#' ## numeric(0)
sdbm_hash <- function(x) {
    .Call('hrbrmiscpp_sdbm_hash', PACKAGE = 'hrbrmiscpp', x)
}

